export const SELECT_ARTICLE = 'SELECT_ARTICLE'
export const REMOVE_ARTICLE = 'REMOVE_ARTICLE'
export const GET_NEW_ARTICLES = 'GET_NEW_ARTICLES'

export const SELECT_SOURCE = 'SELECT_SOURCE'
export const REMOVE_SOURCE = 'REMOVE_SOURCE'

export const INIT_ARTICLES = 'INITAA_ARTICLES'
export const INIT_SOURCES = 'INIT_SOURCES'
